# PreToolUse hook (Edit|Write): blocks edits to generated or vendored paths. Exit 2 = block, with the reason on stderr.
# Never blocks on unexpected input: any failure exits 0.
$ErrorActionPreference = 'Continue'
try {
    $raw = [Console]::In.ReadToEnd()
    if (-not $raw) { exit 0 }
    $j = $raw | ConvertFrom-Json
    $p = $null
    if ($j.tool_input) { $p = $j.tool_input.file_path }
    if (-not $p) { exit 0 }
    $n = ($p -replace '\\', '/')
    $reason = $null
    if ($n -match '/\.godot/') { $reason = '.godot/ is generated by Godot (run tools/import.ps1 instead)' }
    elseif ($n -match '/addons/' -and $env:ALLOW_ADDON_EDIT -ne '1') { $reason = 'addons/ is vendored third-party code (tools/vendor-gut.ps1 manages it; set ALLOW_ADDON_EDIT=1 to override on purpose)' }
    elseif ($n -match '/\.reports/') { $reason = '.reports/ is generated output' }
    elseif ($n -match '/test/baselines/') { $reason = 'test/baselines/ changes only through /approve-baseline' }
    elseif ($n -match '\.import$') { $reason = '*.import files are generated by Godot' }
    elseif ($n -match '/project\.godot$' -and $j.agent_type -and (@('gameplay-dev', 'visuals-dev') -contains $j.agent_type)) {
        $reason = 'project.godot is edited only by the lead on main; report the needed change instead'
    }
    if ($reason) {
        [Console]::Error.WriteLine("BLOCKED by tools/hooks/protect.ps1: $p - $reason")
        exit 2
    }
    exit 0
} catch {
    exit 0
}
